"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { useAuthStore } from "@/store/auth-store";
import { PageHeader } from "@/components/ui/page-header";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import {
  Sliders,
  Clock,
  Zap,
  Bell,
  ShieldCheck,
  Save,
  RotateCcw,
  CheckCircle2,
  AlertCircle,
  HelpCircle,
  Calendar,
  Sparkles,
  ArrowRight,
} from "lucide-react";
import { formatCurrency } from "@/lib/utils";
import { toast } from "sonner";

interface BusinessRulesConfig {
  triageSlaHours: number;
  warningSlaHours: number;
  emergencySlaHours: number;
  arrivalBufferMinutes: number;
  minAdvanceBookingHours: number;
  emergencySurchargePercent: number;
  maxJobsPerTechnician: number;
  notifyOnArrival: boolean;
  notifyOnCompletion: boolean;
  autoGenerateDraftInvoice: boolean;
  autoRequestFeedback: boolean;
}

const DEFAULT_CONFIG: BusinessRulesConfig = {
  triageSlaHours: 24,
  warningSlaHours: 12,
  emergencySlaHours: 4,
  arrivalBufferMinutes: 30,
  minAdvanceBookingHours: 4,
  emergencySurchargePercent: 25,
  maxJobsPerTechnician: 4,
  notifyOnArrival: true,
  notifyOnCompletion: true,
  autoGenerateDraftInvoice: true,
  autoRequestFeedback: true,
};

export default function AdminBusinessRulesPage() {
  const { role } = useAuthStore();
  const [config, setConfig] = useState<BusinessRulesConfig>(DEFAULT_CONFIG);
  const [isSaved, setIsSaved] = useState(false);
  const [testBasePrice, setTestBasePrice] = useState(1000);
  const [testIsEmergency, setTestIsEmergency] = useState(false);

  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("servisync_business_rules");
      if (saved) {
        try {
          setConfig(JSON.parse(saved));
        } catch {}
      }
    }
  }, []);

  const handleSave = () => {
    if (typeof window !== "undefined") {
      localStorage.setItem("servisync_business_rules", JSON.stringify(config));
    }
    setIsSaved(true);
    toast.success("Business rules & scheduling policies saved successfully!");
    setTimeout(() => setIsSaved(false), 3000);
  };

  const handleReset = () => {
    if (confirm("Reset all operational business rules to factory system defaults?")) {
      setConfig(DEFAULT_CONFIG);
      if (typeof window !== "undefined") {
        localStorage.setItem("servisync_business_rules", JSON.stringify(DEFAULT_CONFIG));
      }
      toast.info("Rules reset to platform defaults.");
    }
  };

  // Test calculations
  const surchargeAmount = testIsEmergency
    ? Math.round((testBasePrice * config.emergencySurchargePercent) / 100)
    : 0;
  const simulatedTotal = testBasePrice + surchargeAmount;

  return (
    <div className="space-y-6 max-w-5xl mx-auto">
      <PageHeader
        title="Operational Business Rules & Scheduling"
        description="Configure platform-wide SLA windows, technician dispatch buffers, emergency pricing rules, and automated workflow triggers."
      >
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm" onClick={handleReset} className="rounded-xl text-xs h-8">
            <RotateCcw className="mr-1.5 h-3.5 w-3.5" />
            Reset Defaults
          </Button>
          <Button
            size="sm"
            onClick={handleSave}
            className="rounded-xl text-xs h-8 bg-primary text-primary-foreground shadow-sm"
          >
            {isSaved ? (
              <>
                <CheckCircle2 className="mr-1.5 h-3.5 w-3.5 text-emerald-400" /> Saved!
              </>
            ) : (
              <>
                <Save className="mr-1.5 h-3.5 w-3.5" /> Save Changes
              </>
            )}
          </Button>
        </div>
      </PageHeader>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* Left Column: Rules Editors */}
        <div className="lg:col-span-8 space-y-6">
          {/* Section 1: SLA & Triage Windows */}
          <Card className="rounded-2xl border border-slate-200/80 dark:border-slate-800/80 bg-white/90 dark:bg-[#0c1427]/85 shadow-sm">
            <CardHeader className="pb-3">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <CardTitle className="text-base font-bold flex items-center gap-2">
                  <Clock className="h-4 w-4 text-blue-500" />
                  Service Level Agreement (SLA) Targets
                </CardTitle>
                <Badge variant="outline" className="text-[10px] w-fit">
                  Enforced in Manager Dashboard
                </Badge>
              </div>
              <CardDescription className="text-xs">
                Defines the maximum acceptable review duration before tickets escalate in the manager triage queue.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-xs">
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
                <div className="space-y-1.5">
                  <Label htmlFor="triageSla">Standard SLA (Hours)</Label>
                  <Input
                    id="triageSla"
                    type="number"
                    min="1"
                    max="72"
                    value={config.triageSlaHours}
                    onChange={(e) =>
                      setConfig({ ...config, triageSlaHours: Number(e.target.value) || 24 })
                    }
                    className="text-xs h-9"
                  />
                  <span className="text-[10px] text-muted-foreground">Default: 24 hours</span>
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="warningSla">Warning Window (Hours)</Label>
                  <Input
                    id="warningSla"
                    type="number"
                    min="1"
                    max="48"
                    value={config.warningSlaHours}
                    onChange={(e) =>
                      setConfig({ ...config, warningSlaHours: Number(e.target.value) || 12 })
                    }
                    className="text-xs h-9"
                  />
                  <span className="text-[10px] text-muted-foreground">Flags yellow alert in queue</span>
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="emergencySla">Emergency SLA (Hours)</Label>
                  <Input
                    id="emergencySla"
                    type="number"
                    min="1"
                    max="12"
                    value={config.emergencySlaHours}
                    onChange={(e) =>
                      setConfig({ ...config, emergencySlaHours: Number(e.target.value) || 4 })
                    }
                    className="text-xs h-9"
                  />
                  <span className="text-[10px] text-muted-foreground">Priority expedite target</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Section 2: Scheduling & Dispatch Policy */}
          <Card className="rounded-2xl border border-slate-200/80 dark:border-slate-800/80 bg-white/90 dark:bg-[#0c1427]/85 shadow-sm">
            <CardHeader className="pb-3">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2">
                <CardTitle className="text-base font-bold flex items-center gap-2">
                  <Calendar className="h-4 w-4 text-emerald-500" />
                  Field Scheduling & Technician Dispatch Policy
                </CardTitle>
                <Badge variant="outline" className="text-[10px] w-fit">
                  Dispatch Assistant
                </Badge>
              </div>
              <CardDescription className="text-xs">
                Controls travel buffers, minimum advance booking lead-time, and workload caps.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-xs">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label htmlFor="arrivalBuffer">Technician Transit Buffer (Minutes)</Label>
                  <Input
                    id="arrivalBuffer"
                    type="number"
                    min="0"
                    max="120"
                    value={config.arrivalBufferMinutes}
                    onChange={(e) =>
                      setConfig({ ...config, arrivalBufferMinutes: Number(e.target.value) || 30 })
                    }
                    className="text-xs h-9"
                  />
                  <span className="text-[10px] text-muted-foreground">
                    Required travel buffer between consecutive jobs
                  </span>
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="advanceBooking">Min. Booking Notice (Hours)</Label>
                  <Input
                    id="advanceBooking"
                    type="number"
                    min="1"
                    max="48"
                    value={config.minAdvanceBookingHours}
                    onChange={(e) =>
                      setConfig({ ...config, minAdvanceBookingHours: Number(e.target.value) || 4 })
                    }
                    className="text-xs h-9"
                  />
                  <span className="text-[10px] text-muted-foreground">
                    Minimum lead time for non-emergency bookings
                  </span>
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="emergencySurcharge">Emergency Surcharge Rate (%)</Label>
                  <Input
                    id="emergencySurcharge"
                    type="number"
                    min="0"
                    max="100"
                    value={config.emergencySurchargePercent}
                    onChange={(e) =>
                      setConfig({
                        ...config,
                        emergencySurchargePercent: Number(e.target.value) || 25,
                      })
                    }
                    className="text-xs h-9"
                  />
                  <span className="text-[10px] text-muted-foreground">
                    Applied on rapid-response expedited bookings
                  </span>
                </div>

                <div className="space-y-1.5">
                  <Label htmlFor="maxJobs">Max Active Jobs / Technician</Label>
                  <Input
                    id="maxJobs"
                    type="number"
                    min="1"
                    max="10"
                    value={config.maxJobsPerTechnician}
                    onChange={(e) =>
                      setConfig({ ...config, maxJobsPerTechnician: Number(e.target.value) || 4 })
                    }
                    className="text-xs h-9"
                  />
                  <span className="text-[10px] text-muted-foreground">
                    Prevents technician dispatch overloading
                  </span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Section 3: Notification & Automation Rules */}
          <Card className="rounded-2xl border border-slate-200/80 dark:border-slate-800/80 bg-white/90 dark:bg-[#0c1427]/85 shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-base font-bold flex items-center gap-2">
                <Bell className="h-4 w-4 text-purple-500" />
                Notification & Automation Rules
              </CardTitle>
              <CardDescription className="text-xs">
                Automated event triggers executed during work order and payment transitions.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-3 text-xs">
              <div
                onClick={() => setConfig({ ...config, notifyOnArrival: !config.notifyOnArrival })}
                className="p-3 rounded-xl border border-border/70 flex items-center justify-between cursor-pointer hover:border-primary/40 transition-colors"
              >
                <div>
                  <p className="font-bold text-foreground">Arrival Notifications</p>
                  <p className="text-[11px] text-muted-foreground">
                    Notify customer via SMS and email when technician logs on-site arrival.
                  </p>
                </div>
                <Badge variant={config.notifyOnArrival ? "success" : "secondary"}>
                  {config.notifyOnArrival ? "Enabled" : "Disabled"}
                </Badge>
              </div>

              <div
                onClick={() =>
                  setConfig({ ...config, notifyOnCompletion: !config.notifyOnCompletion })
                }
                className="p-3 rounded-xl border border-border/70 flex items-center justify-between cursor-pointer hover:border-primary/40 transition-colors"
              >
                <div>
                  <p className="font-bold text-foreground">Service Completion Event</p>
                  <p className="text-[11px] text-muted-foreground">
                    Broadcast verified completion to customer and initialize 30-day warranty timeline.
                  </p>
                </div>
                <Badge variant={config.notifyOnCompletion ? "success" : "secondary"}>
                  {config.notifyOnCompletion ? "Enabled" : "Disabled"}
                </Badge>
              </div>

              <div
                onClick={() =>
                  setConfig({
                    ...config,
                    autoGenerateDraftInvoice: !config.autoGenerateDraftInvoice,
                  })
                }
                className="p-3 rounded-xl border border-border/70 flex items-center justify-between cursor-pointer hover:border-primary/40 transition-colors"
              >
                <div>
                  <p className="font-bold text-foreground">Automatic Invoicing Trigger</p>
                  <p className="text-[11px] text-muted-foreground">
                    Prompt managers to generate payable Stripe invoice immediately upon job wrap-up.
                  </p>
                </div>
                <Badge variant={config.autoGenerateDraftInvoice ? "success" : "secondary"}>
                  {config.autoGenerateDraftInvoice ? "Enabled" : "Disabled"}
                </Badge>
              </div>

              <div
                onClick={() =>
                  setConfig({ ...config, autoRequestFeedback: !config.autoRequestFeedback })
                }
                className="p-3 rounded-xl border border-border/70 flex items-center justify-between cursor-pointer hover:border-primary/40 transition-colors"
              >
                <div>
                  <p className="font-bold text-foreground">Feedback Solicitation</p>
                  <p className="text-[11px] text-muted-foreground">
                    Prompt customer for 1-to-5 star rating and review after verified service completion.
                  </p>
                </div>
                <Badge variant={config.autoRequestFeedback ? "success" : "secondary"}>
                  {config.autoRequestFeedback ? "Enabled" : "Disabled"}
                </Badge>
              </div>
            </CardContent>
          </Card>
        </div>

        {/* Right Column: Rule Simulator & Summary */}
        <div className="lg:col-span-4 space-y-6">
          <Card className="rounded-2xl border border-primary/30 bg-primary/5 shadow-sm">
            <CardHeader className="pb-2">
              <CardTitle className="text-sm font-bold flex items-center gap-1.5 text-primary">
                <Sparkles className="h-4 w-4" />
                Live Rule Policy Simulator
              </CardTitle>
              <CardDescription className="text-xs">
                Test how configured policies calculate on customer orders.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 text-xs">
              <div className="space-y-1.5">
                <Label htmlFor="testBase">Simulated Service Fee (৳)</Label>
                <Input
                  id="testBase"
                  type="number"
                  min="0"
                  value={testBasePrice}
                  onChange={(e) => setTestBasePrice(Number(e.target.value) || 0)}
                  className="text-xs h-8"
                />
              </div>

              <div
                onClick={() => setTestIsEmergency(!testIsEmergency)}
                className="p-2.5 rounded-lg border border-border bg-card flex items-center justify-between cursor-pointer hover:border-primary/40"
              >
                <div>
                  <span className="font-bold block">Simulate Emergency Booking</span>
                  <span className="text-[10px] text-muted-foreground">
                    Applies +{config.emergencySurchargePercent}% fee & {config.emergencySlaHours}h SLA
                  </span>
                </div>
                <Badge variant={testIsEmergency ? "destructive" : "outline"}>
                  {testIsEmergency ? "Active" : "Normal"}
                </Badge>
              </div>

              <div className="p-3 rounded-xl bg-card border border-border space-y-2">
                <div className="flex items-center justify-between text-muted-foreground">
                  <span>Base Labor:</span>
                  <span>{formatCurrency(testBasePrice, "BDT")}</span>
                </div>
                {testIsEmergency && (
                  <div className="flex items-center justify-between text-amber-600 font-semibold">
                    <span>Emergency Surcharge:</span>
                    <span>+{formatCurrency(surchargeAmount, "BDT")}</span>
                  </div>
                )}
                <div className="flex items-center justify-between text-muted-foreground">
                  <span>Arrival Buffer:</span>
                  <span>{config.arrivalBufferMinutes} mins</span>
                </div>
                <div className="flex items-center justify-between text-muted-foreground">
                  <span>Triage SLA Target:</span>
                  <span>{testIsEmergency ? config.emergencySlaHours : config.triageSlaHours} hours</span>
                </div>
                <div className="pt-2 border-t border-border flex items-center justify-between font-bold text-sm text-foreground">
                  <span>Calculated Payable:</span>
                  <span className="text-primary">{formatCurrency(simulatedTotal, "BDT")}</span>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Quick Info Box */}
          <Card className="rounded-2xl border border-slate-200/80 dark:border-slate-800/80 bg-white/90 dark:bg-[#0c1427]/85 p-4 text-xs space-y-2">
            <h4 className="font-bold text-foreground flex items-center gap-1.5">
              <ShieldCheck className="h-4 w-4 text-emerald-500" />
              Policy Governance
            </h4>
            <p className="text-muted-foreground leading-relaxed">
              Rules modified here take immediate effect across customer booking validators, technician dispatch buffers, and manager triage SLA monitors.
            </p>
          </Card>
        </div>
      </div>
    </div>
  );
}
